# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainVentana.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#Llamada a ventanas(clases)
from screen4 import Ui_analisis4
from screen5 import Ui_analisis5
from screen6 import Ui_analisis6

class Ui_MainWindow(object):
        #Funciones analisis
    def openAna4(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_analisis4()
        self.ui.setupUi(self.window)
        self.window.show()

    def openAna5(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_analisis5()
        self.ui.setupUi(self.window)
        self.window.show()

    def openAna6(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_analisis6()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 821)
        MainWindow.setMinimumSize(QtCore.QSize(1057, 821))
        MainWindow.setMaximumSize(QtCore.QSize(1057, 821))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 206, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 50, 461, 71))
        self.label.setStyleSheet("color: rgb(255, 15, 159);\n"
"font: 75 28pt \"Comic Sans MS\";\n"
"")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 210, 171, 61))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 129, 255);\n"
"font: 60 18pt \"Rockwell\";\n"
"border-color: rgb(180, 126, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 360, 171, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 129, 255);\n"
"font: 60 18pt \"Rockwell\";\n"
"border-color: rgb(180, 126, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 510, 171, 61))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 129, 255);\n"
"font: 60 18pt \"Rockwell\";\n"
"border-color: rgb(180, 126, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.openAna4())
        self.pushButton_4.setGeometry(QtCore.QRect(650, 210, 171, 61))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 129, 255);\n"
"font: 60 18pt \"Rockwell\";\n"
"border-color: rgb(180, 126, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.openAna5())
        self.pushButton_5.setGeometry(QtCore.QRect(650, 360, 171, 61))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 129, 255);\n"
"font: 60 18pt \"Rockwell\";\n"
"border-color: rgb(180, 126, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.openAna6())
        self.pushButton_6.setGeometry(QtCore.QRect(650, 510, 171, 61))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 129, 255);\n"
"font: 60 18pt \"Rockwell\";\n"
"border-color: rgb(180, 126, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Búsqueda de empleos"))
        self.pushButton.setText(_translate("MainWindow", "Análisis 1"))
        self.pushButton_2.setText(_translate("MainWindow", "Análisis 2"))
        self.pushButton_3.setText(_translate("MainWindow", "Análisis 3"))
        self.pushButton_4.setText(_translate("MainWindow", "Análisis 4"))
        self.pushButton_5.setText(_translate("MainWindow", "Análisis 5"))
        self.pushButton_6.setText(_translate("MainWindow", "Análisis 6"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
