# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#Integrante - Gabriela Sosa
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import numpy as np
import csv

class Ui_analisis4(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 821)
        MainWindow.setMinimumSize(QtCore.QSize(1057, 821))
        MainWindow.setMaximumSize(QtCore.QSize(1057, 821))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 206, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 20, 521, 71))
        self.label.setStyleSheet("color: rgb(255, 15, 159);\n"
"font: 75 23pt \"Comic Sans MS\";\n"
"")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.hide())
        self.pushButton_3.setGeometry(QtCore.QRect(30, 30, 101, 31))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 129, 255);\n"
"font: 60 12pt \"Rockwell\";\n"
"border-color: rgb(180, 126, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 80, 641, 71))
        self.label_2.setStyleSheet("color:rgb(150, 129, 255);\n"
"font: 75 16pt \"Comic Sans MS\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 720, 1011, 51))
        self.label_3.setStyleSheet("font: 11pt \"Comic Sans MS\";\n"
"")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 750, 1011, 51))
        self.label_4.setStyleSheet("font: 11pt \"Comic Sans MS\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 160, 931, 551))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        #plot
        self.figure=plt.figure()
        self.canvas=FigureCanvas(self.figure)
        self.horizontalLayout.addWidget(self.canvas)
        #end plot
        #mostrar plot
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.plotOnCanvas())
        self.pushButton_4.setGeometry(QtCore.QRect(30, 70, 101, 31))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 129, 255);\n"
"font: 60 12pt \"Rockwell\";\n"
"border-color: rgb(180, 126, 255);")
        
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Gráfico de barras agrupadas"))
        self.pushButton_3.setText(_translate("MainWindow", "Regresar"))
        self.label_2.setText(_translate("MainWindow", "Ofertas de trabajo por áreas: Guayaquil vs. Quito"))
        self.pushButton_4.setText(_translate("MainWindow", "Graficar"))

    def plotOnCanvas(self):
        self.figure.clear()
        x = np.arange(6) 
        with open('datos.csv','rt')as f:
                data = csv.reader(f)
                for row in data:
                        if(row.count('Pregunta4')):
                                values1=row[1:7]
                                values2=row[7:]
        width=0.40
        valuesGye = [eval(i) for i in values1]
        valuesQio = [eval(i) for i in values2]
        plt.xticks(x, ['Informática','Administración','Logística','Ventas','Turismo','Salud'])
        plt.bar(x-0.2, valuesGye, width,color='red') 
        plt.bar(x+0.2, valuesQio, width,color='cyan')
        plt.xlabel("Área de trabajo")
        plt.ylabel("Cantidad de empleos")
        plt.legend(["Guayaquil", "Quito"]) 
        plt.title('Integrante: Gabriela Sosa')
        self.label_3.setText("En Quito hay más trabajos en el área de informática que en Guayaquil.")
        self.label_4.setText("Existe poca oferta de trabajos en el área de informática a comparación de áreas como ventas y administración.")
        self.canvas.draw()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_analisis4()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
