# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#Integrante - Gabriela Sosa
from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from numpy import random
import csv

class Ui_analisis5(object):
    def setupUi(self, analisis5):
        analisis5.setObjectName("analisis5")
        analisis5.resize(1057, 821)
        analisis5.setMinimumSize(QtCore.QSize(1057, 821))
        analisis5.setMaximumSize(QtCore.QSize(1057, 821))
        analisis5.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 206, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(analisis5)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 20, 311, 71))
        self.label.setStyleSheet("color: rgb(255, 15, 159);\n"
"font: 75 23pt \"Comic Sans MS\";\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 80, 621, 71))
        self.label_2.setStyleSheet("color:rgb(150, 129, 255);\n"
"font: 75 16pt \"Comic Sans MS\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 720, 1011, 51))
        self.label_3.setStyleSheet("font: 12pt \"Comic Sans MS\";\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 160, 931, 551))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
         #plot
        self.figure=plt.figure()
        self.canvas=FigureCanvas(self.figure)
        self.horizontalLayout.addWidget(self.canvas)
        #end plot

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.plotOnCanvas())
        self.pushButton_4.setGeometry(QtCore.QRect(70, 60, 101, 31))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 129, 255);\n"
"font: 60 12pt \"Rockwell\";\n"
"border-color: rgb(180, 126, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        analisis5.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(analisis5)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 26))
        self.menubar.setObjectName("menubar")
        analisis5.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(analisis5)
        self.statusbar.setObjectName("statusbar")
        analisis5.setStatusBar(self.statusbar)

        self.retranslateUi(analisis5)
        QtCore.QMetaObject.connectSlotsByName(analisis5)

    def retranslateUi(self, analisis5):
        _translate = QtCore.QCoreApplication.translate
        analisis5.setWindowTitle(_translate("analisis5", "MainWindow"))
        self.label.setText(_translate("analisis5", "Gráfico de barras"))
        self.label_2.setText(_translate("analisis5", "Ofertas de trabajo por áreas: salarios promedios"))
        self.pushButton_4.setText(_translate("analisis5", "Graficar"))

    def plotOnCanvas(self):
        self.figure.clear()
        colors='purple', 'red','pink', 'yellow', 'blue','cyan'
        labels=['Desarrollador',' A. administración','Contador','Vendedor','Técnico mecánico','Recepcionista']
        with open('datos.csv','rt')as f:
                data = csv.reader(f)
                for row in data:
                        if(row.count('Pregunta5')):
                                values=row[1:]
        valuesGye = [eval(i) for i in values]
        plt.bar(labels,valuesGye,color=colors,width=0.5)
        plt.xlabel("Ofertas de empleo en Guayaquil o remoto")
        plt.ylabel("Salario promedio (ec.jooble.com)")
        plt.title("Integrante - Gabriela Sosa")
        self.label_3.setText("El trabajo mejor remunerado en Guayaquil o de forma remota es el de desarrollador.")
        self.canvas.draw()
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    analisis5 = QtWidgets.QMainWindow()
    ui = Ui_analisis5()
    ui.setupUi(analisis5)
    analisis5.show()
    sys.exit(app.exec_())
